Moved leaderboard back button to upper left to improve user experienc…
ucsb-cs156-w24/proj-happy-cows-w24-4pm-1 pull request #12
Opened 2024-02-23 01:21 UTC by TianyiYang-Tyler

…e - T. Yang

## Overview

In this PR, move back button on leadership board to improve user experience

## Future Possibilities (Optional)

Some possible points could be:
- This is the beginning/part of improving UX
- This can make things easier to 

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #3

2024-02-23 01:51 UTC, sangitakunapuli requested changes
Could you provide images of the UI before and after your change?

2024-02-23 02:15 UTC, TianyiYang-Tyler commented
Screenshot of leaderboard before & after button positioning change posted.

2024-02-23 02:30 UTC, sangitakunapuli approved these changes
LGTM

2024-02-24 21:36 UTC, jtanggy approved these changes

2024-02-29 00:36 UTC, merged